version: "3.8"
services:
  event-ingestion:
    build: ./event-ingestion
    ports:
      - "3000:3000"
    depends_on:
      - kafka
    environment:
      - PORT=3000

  ride-matching:
    build: ./ride-matching
    ports:
      - "3001:3001"
    depends_on:
      - kafka
      - redis
    environment:
      - PORT=3001

  payment-processing:
    build: ./payment-processing
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
    environment:
      - PORT=3002

  monitoring:
    build: ./monitoring
    ports:
      - "3003:3003"
    depends_on:
      - prometheus
      - grafana
    environment:
      - PORT=3003

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  redis:
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3004:3000"
